spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/recitewords1?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


    #连接池的配置信息
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  thymeleaf:
    cache: false
  mail:
    host: smtp.163.com
    username: Y13262639708@163.com
    password: YUAN199638
    default-encoding: UTF-8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1024MB

#指定MyBatis配置文件
mybatis:
  config-location: classpath:mybatis_config.xml
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    context-path: /recitewords

#文件上传路径
file:
  upload-dir: D:/Users/uploads